<?php
use App\Model\Entity\AlbumEntity;

$this->layout('layout::default', ['title' => 'Create new album']);
?>

<div class="jumbotron">
    <h1>Create new album</h1>
</div>

<div class="alert alert-danger">
    <strong><?php echo $message ?></strong>
</div>

<div class="card">
    <form class="form-horizontal" action="<?php echo $this->url('album.create.handle') ?>" method="post">
    <!--<div class="container">-->
        <div class="form-group form-row">
            <label for="artist" class="col-sm-2 col-form-label">Artist:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="artist" name="artist">
            </div>
        </div>
        
        <div class="form-group form-row">
            <label for="title" class="col-sm-2 col-form-label">Title:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title">
            </div>
        </div>
        
        <div class="form-group form-row">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Album</button>
            </div>
        </div>
    <!--</div>-->
    </form>
</div>

<p>
    <a href="<?php echo $this->url('album.list') ?>" class="btn btn-success">Back to album list</a>
</p>